// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: setstatus.sql

package sqlc

import (
	"context"
)

const setOrderStatus = `-- name: SetOrderStatus :exec
UPDATE "orders"
SET status = $2
WHERE order_id = $1
`

type SetOrderStatusParams struct {
	OrderID int64
	Status  OrderStatus
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.OrderID, arg.Status)
	return err
}
