scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cart'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:8082"
          
  - job_name: 'loms'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "host.docker.internal:8084"
