// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: getbysku.sql

package sqlc

import (
	"context"
)

const getBySKU = `-- name: GetBySKU :one
SELECT sku, total_count, reserved
FROM items
WHERE sku = $1
`

type GetBySKURow struct {
	Sku        int32
	TotalCount int32
	Reserved   int32
}

func (q *Queries) GetBySKU(ctx context.Context, sku int32) (GetBySKURow, error) {
	row := q.db.QueryRow(ctx, getBySKU, sku)
	var i GetBySKURow
	err := row.Scan(&i.Sku, &i.TotalCount, &i.Reserved)
	return i, err
}
