// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: createorderstatus.sql

package sqlc

import (
	"context"
)

const createOrderStatusChangedEvent = `-- name: CreateOrderStatusChangedEvent :exec
INSERT INTO order_status_changed_events (order_id, status)
VALUES ($1, $2)
`

type CreateOrderStatusChangedEventParams struct {
	OrderID int64
	Status  OrderStatus
}

func (q *Queries) CreateOrderStatusChangedEvent(ctx context.Context, arg CreateOrderStatusChangedEventParams) error {
	_, err := q.db.Exec(ctx, createOrderStatusChangedEvent, arg.OrderID, arg.Status)
	return err
}
