// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: markorderstatusassend.sql

package sqlc

import (
	"context"
)

const markOrderStatusChangedEventAsSend = `-- name: MarkOrderStatusChangedEventAsSend :exec
UPDATE order_status_changed_events
SET sent = TRUE
WHERE id = $1
`

func (q *Queries) MarkOrderStatusChangedEventAsSend(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOrderStatusChangedEventAsSend, id)
	return err
}
